### ISSUE TITLE
TODO for initial release

### ISSUE THREAD

**Issue by mfussenegger** [mfussenegger/hprofdap#1]
- [ ] jlink/native image?
- [ ] Get more complex queries to work
- [ ] Add missing/required protocol handlers
- [ ] Make errors more verbose - "Internal error" is not helpful
- [ ] Tweak variable output formatting for various types
- [ ] Maybe add some predefined queries or special expressions like `summary`, `dominators`, `gc_roots`
- [ ] Add license
